language: node_js

branches:
  only:
    - master
    - develop

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - node

script:
  - mkdir ./reports
  - yarn test:ci
  - yarn danger ci
